### ISSUE TITLE
Fast minecarts on fabric 1.20.1 requires java 21

### ISSUE THREAD

**Issue by flexape13** [Bestsoft101/SmallMods#1]
Looks like mod is compiled against java 21, as it doesn't allow the game to start on java 17 or 18.

**Comment by flexape13** [comment]
![photo_2024-10-27_00-48-47](https://github.com/user-attachments/assets/396026a3-56fe-45a3-8e00-d99e3803ec62)

**Comment by Bestsoft101** [comment]
Fixed in 1.0.2
